In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = sns.load_dataset('tips')

In [3]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
# predict what is the time? if any one visiting -- is it lunch or dinner? time is the target variable

df.time.unique()


['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [5]:
# encoding,missing value treatment,scaling>> automate

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [6]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [7]:
# categorical to numerical

from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['time'] = encoder.fit_transform(df['time'])
df

total_bill   tip     sex smoker   day  time  size
0         16.99  1.01  Female     No   Sun     0     2
1         10.34  1.66    Male     No   Sun     0     3
2         21.01  3.50    Male     No   Sun     0     3
3         23.68  3.31    Male     No   Sun     0     2
4         24.59  3.61  Female     No   Sun     0     4
..          ...   ...     ...    ...   ...   ...   ...
239       29.03  5.92    Male     No   Sat     0     3
240       27.18  2.00  Female    Yes   Sat     0     2
241       22.67  2.00    Male    Yes   Sat     0     2
242       17.82  1.75    Male     No   Sat     0     2
243       18.78  3.00  Female     No  Thur     0     2

[244 rows x 7 columns]

In [8]:
df['time'].unique()

array([0, 1])

In [9]:
x = df.drop('time',axis=1)
y = df['time']

In [10]:
x

total_bill   tip     sex smoker   day  size
0         16.99  1.01  Female     No   Sun     2
1         10.34  1.66    Male     No   Sun     3
2         21.01  3.50    Male     No   Sun     3
3         23.68  3.31    Male     No   Sun     2
4         24.59  3.61  Female     No   Sun     4
..          ...   ...     ...    ...   ...   ...
239       29.03  5.92    Male     No   Sat     3
240       27.18  2.00  Female    Yes   Sat     2
241       22.67  2.00    Male    Yes   Sat     2
242       17.82  1.75    Male     No   Sat     2
243       18.78  3.00  Female     No  Thur     2

[244 rows x 6 columns]

In [11]:
y

0      0
1      0
2      0
3      0
4      0
      ..
239    0
240    0
241    0
242    0
243    0
Name: time, Length: 244, dtype: int64

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [15]:
x_train

total_bill   tip     sex smoker   day  size
0         16.99  1.01  Female     No   Sun     2
154       19.77  2.00    Male     No   Sun     4
167       31.71  4.50    Male     No   Sun     4
110       14.00  3.00    Male     No   Sat     2
225       16.27  2.50  Female    Yes   Fri     2
..          ...   ...     ...    ...   ...   ...
137       14.15  2.00  Female     No  Thur     2
72        26.86  3.14  Female    Yes   Sat     2
140       17.47  3.50  Female     No  Thur     2
235       10.07  1.25    Male     No   Sat     2
37        16.93  3.07  Female     No   Sat     3

[195 rows x 6 columns]

In [16]:
# handling the missing values
# data encoding
# feature scaling

from sklearn.impute import SimpleImputer #missing value
from sklearn.preprocessing import OneHotEncoder #encoding
from sklearn.preprocessing import StandardScaler #scaling

from sklearn.pipeline import Pipeline #sequence of data transformer
from sklearn.compose import ColumnTransformer # groups all the pipeline steps for each of the col

In [17]:
df

total_bill   tip     sex smoker   day  time  size
0         16.99  1.01  Female     No   Sun     0     2
1         10.34  1.66    Male     No   Sun     0     3
2         21.01  3.50    Male     No   Sun     0     3
3         23.68  3.31    Male     No   Sun     0     2
4         24.59  3.61  Female     No   Sun     0     4
..          ...   ...     ...    ...   ...   ...   ...
239       29.03  5.92    Male     No   Sat     0     3
240       27.18  2.00  Female    Yes   Sat     0     2
241       22.67  2.00    Male    Yes   Sat     0     2
242       17.82  1.75    Male     No   Sat     0     2
243       18.78  3.00  Female     No  Thur     0     2

[244 rows x 7 columns]

In [18]:
df.sample(1)

total_bill  tip     sex smoker  day  time  size
223       15.98  3.0  Female     No  Fri     1     3

In [19]:
cat_cols = ['sex','smoker','day']
num_cols = ['total_bill','tip','size']

In [20]:
# feature engineering automation using pipeline and col transformer

num_pipeline = Pipeline( steps=[ ('imputation',SimpleImputer(strategy='median')),
       ('scaling',StandardScaler())])

cat_pipeline = Pipeline(steps=[ ('imputation',SimpleImputer(strategy='most_frequent')),
       ('onehot',OneHotEncoder())])


In [23]:
preprocessor = ColumnTransformer([('num_pipeline',num_pipeline,num_cols),
                   ('cat_pipeline',cat_pipeline,cat_cols)])
preprocessor

ColumnTransformer(transformers=[('num_pipeline',
                                 Pipeline(steps=[('imputation',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaling',
                                                  StandardScaler())]),
                                 ['total_bill', 'tip', 'size']),
                                ('cat_pipeline',
                                 Pipeline(steps=[('imputation',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehot', OneHotEncoder())]),
                                 ['sex', 'smoker', 'day'])])

In [24]:
x_train = preprocessor.fit_transform(x_train)
x_test = preprocessor.transform(x_test)

In [25]:
x_train

array([[-0.28611937, -1.47443803, -0.57766863, ...,  0.        ,
         1.        ,  0.        ],
       [ 0.02695905, -0.71612531,  1.47042924, ...,  0.        ,
         1.        ,  0.        ],
       [ 1.3716196 ,  1.19880579,  1.47042924, ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [-0.23206267,  0.43283335, -0.57766863, ...,  0.        ,
         0.        ,  1.        ],
       [-1.06543688, -1.29060464, -0.57766863, ...,  1.        ,
         0.        ,  0.        ],
       [-0.29287646,  0.1034652 ,  0.44638031, ...,  1.        ,
         0.        ,  0.        ]])

In [26]:
x_test

array([[-1.85376383, -1.48209775, -1.60171757,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [-0.08453291,  0.04984713, -0.57766863,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [ 0.79501474,  0.36389583,  0.44638031,  0.        ,  1.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [-0.59356688, -0.33313909, -0.57766863,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [ 0.18349826,  0.04984713, -0.57766863,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [-1.32783714, -1.14506988, -0.57766863,  0.        ,  1.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.   

In [27]:
# Building the multiple models

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

In [28]:
models = {'support vector classifier':SVC(),
          'DT classifier':DecisionTreeClassifier(),
          'Log reg':LogisticRegression()}

In [29]:
models

{'support vector classifier': SVC(),
 'DT classifier': DecisionTreeClassifier(),
 'Log reg': LogisticRegression()}

In [30]:
for i in range(len(models)):
  print(list(models.values())[i])

SVC()
DecisionTreeClassifier()
LogisticRegression()


In [34]:
from sklearn.metrics import accuracy_score

def model_train_eval(x_train,y_train,x_test,y_test,models):
  evaluation = {}
  for i in range (len(models)):
    model = list(models.values())[i]
    model.fit(x_train,y_train)
    y_pred = model.predict(x_test)
    model_score = accuracy = accuracy_score(y_test,y_pred)
    evaluation[list(models.keys())[i]] = model_score
  return evaluation

In [35]:
model_train_eval(x_train,y_train,x_test,y_test,models)

{'support vector classifier': 0.9183673469387755,
 'DT classifier': 0.9183673469387755,
 'Log reg': 0.9183673469387755}

# Random forest classifier


In [36]:
from sklearn.ensemble import RandomForestClassifier
rf =  RandomForestClassifier()
rf

RandomForestClassifier()

In [37]:
x_train

array([[-0.28611937, -1.47443803, -0.57766863, ...,  0.        ,
         1.        ,  0.        ],
       [ 0.02695905, -0.71612531,  1.47042924, ...,  0.        ,
         1.        ,  0.        ],
       [ 1.3716196 ,  1.19880579,  1.47042924, ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [-0.23206267,  0.43283335, -0.57766863, ...,  0.        ,
         0.        ,  1.        ],
       [-1.06543688, -1.29060464, -0.57766863, ...,  1.        ,
         0.        ,  0.        ],
       [-0.29287646,  0.1034652 ,  0.44638031, ...,  1.        ,
         0.        ,  0.        ]])

In [38]:
x_test

array([[-1.85376383, -1.48209775, -1.60171757,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [-0.08453291,  0.04984713, -0.57766863,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [ 0.79501474,  0.36389583,  0.44638031,  0.        ,  1.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [-0.59356688, -0.33313909, -0.57766863,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [ 0.18349826,  0.04984713, -0.57766863,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [-1.32783714, -1.14506988, -0.57766863,  0.        ,  1.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.   

In [43]:
# hyper parameter tuning
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV

In [44]:
params = {'max_depth':[1,2,3,4,5,10,None],
          'n_estimators': [30,40,50,100,200,300],
          'criterion':['gini','entropy']}

In [45]:
params

{'max_depth': [1, 2, 3, 4, 5, 10, None],
 'n_estimators': [30, 40, 50, 100, 200, 300],
 'criterion': ['gini', 'entropy']}

In [46]:
clf = RandomizedSearchCV(rf,param_distributions=params,n_iter=10,cv=5,verbose=2,scoring='accuracy')

In [47]:
clf

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(),
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': [1, 2, 3, 4, 5, 10, None],
                                        'n_estimators': [30, 40, 50, 100, 200,
                                                         300]},
                   scoring='accuracy', verbose=2)

In [48]:
clf.fit(x_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV] END ...criterion=gini, max_depth=None, n_estimators=200; total time=   0.5s
[CV] END ...criterion=gini, max_depth=None, n_estimators=200; total time=   0.7s
[CV] END ...criterion=gini, max_depth=None, n_estimators=200; total time=   0.4s
[CV] END ...criterion=gini, max_depth=None, n_estimators=200; total time=   0.4s
[CV] END ...criterion=gini, max_depth=None, n_estimators=200; total time=   0.4s
[CV] END .......criterion=gini, max_depth=2, n_estimators=30; total time=   0.1s
[CV] END .......criterion=gini, max_depth=2, n_estimators=30; total time=   0.1s
[CV] END .......criterion=gini, max_depth=2, n_estimators=30; total time=   0.1s
[CV] END .......criterion=gini, max_depth=2, n_estimators=30; total time=   0.1s
[CV] END .......criterion=gini, max_depth=2, n_estimators=30; total time=   0.1s
[CV] END ...criterion=entropy, max_depth=3, n_estimators=200; total time=   0.3s
[CV] END ...criterion=entropy, max_depth=3, n_es

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(),
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': [1, 2, 3, 4, 5, 10, None],
                                        'n_estimators': [30, 40, 50, 100, 200,
                                                         300]},
                   scoring='accuracy', verbose=2)

In [49]:
clf.best_params_

{'n_estimators': 30, 'max_depth': 2, 'criterion': 'gini'}

In [50]:
clf.best_score_

np.float64(0.9794871794871796)

In [51]:
final_model = clf.best_estimator_
final_model.predict(x_test)

array([0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0])

In [52]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [53]:
models = {'support vector classifier':SVC(),
          'DT classifier':DecisionTreeClassifier(),
          'Log reg':LogisticRegression(),
          'random fr':RandomForestClassifier()}

In [54]:
models

{'support vector classifier': SVC(),
 'DT classifier': DecisionTreeClassifier(),
 'Log reg': LogisticRegression(),
 'random fr': RandomForestClassifier()}

In [55]:
for i in range(len(models)):
  print(list(models.values())[i])

SVC()
DecisionTreeClassifier()
LogisticRegression()
RandomForestClassifier()


In [56]:
from sklearn.metrics import accuracy_score

def model_train_eval(x_train,y_train,x_test,y_test,models):
  evaluation = {}
  for i in range (len(models)):
    model = list(models.values())[i]
    model.fit(x_train,y_train)
    y_pred = model.predict(x_test)
    model_score = accuracy = accuracy_score(y_test,y_pred)
    evaluation[list(models.keys())[i]] = model_score
  return evaluation

In [57]:
model_train_eval(x_train,y_train,x_test,y_test,models)

{'support vector classifier': 0.9183673469387755,
 'DT classifier': 0.9387755102040817,
 'Log reg': 0.9183673469387755,
 'random fr': 0.9183673469387755}

#OOB Score


In [58]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

In [59]:
x,y = make_classification(n_samples = 1000,n_features= 20,n_classes = 2,random_state = 1)

In [60]:
x

array([[-2.04582165, -0.13791624, -0.08071423, ...,  2.48194524,
         0.74236675,  0.23154789],
       [-0.98726024,  1.30120189,  2.37734888, ...,  0.55445754,
        -0.21892143, -0.37608578],
       [ 0.57335921,  0.09375582,  0.4662521 , ..., -0.6088508 ,
         0.79903499, -0.17121177],
       ...,
       [-0.70737159,  1.07650943,  0.58510456, ..., -1.51337602,
         0.90239871, -0.69230951],
       [-0.20706849,  1.17319848, -1.94478665, ..., -0.32820676,
         1.5711921 ,  1.14877729],
       [-2.16769231, -2.54871672,  2.89359255, ...,  0.71535366,
         0.34329241,  1.07350284]])

In [61]:
y

array([0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [63]:
rf_clf = RandomForestClassifier(n_estimators=100,oob_score = True,random_state = 1)
rf_clf

RandomForestClassifier(oob_score=True, random_state=1)

In [64]:
rf_clf.fit(x,y)

RandomForestClassifier(oob_score=True, random_state=1)

In [65]:
rf_clf.oob_score_


0.861